### ISSUE TITLE
La classe de test n'est pas chargée

### ISSUE THREAD

**Issue by PierreGaudichon** [PierreGaudichon/vev-dynamic-testing#1]
On veut récupérer la classe de test.

    	ClassPool pool = ClassPool.getDefault();
    	pool.appendClassPath("src/test/resources/Test1/target/test-classes/istic/fr/prog_test");
    	CtClass cc = pool.get("istic.fr.prog_test.PointTest");

Ici, aucune erreur n'est lancée, mais `cc` semble vide (la plupart de ses attributs sont à `null` ou `false`).

On veut ensuite exécuter les tests.

  	JUnitCore runner = new JUnitCore();
  	runner.addListener(new TextListener(System.out));
  	runner.run(cc.getClass());

A l'exécution des tests, une erreur est lancée:

  	1) initializationError(javassist.CtClassType)
  	java.lang.Exception: The class javassist.CtClassType is not public.

**Comment by nharrand** [comment]
JUnitCore.run demande un paramètre de type Class. Donc une classe java (chargée). 
Javassist travail sur une abstraction(CtClass). 
Après
```java
	ClassPool pool = ClassPool.getDefault();
	pool.appendClassPath("src/test/resources/Test1/target/test-classes/istic/fr/prog_test");
	CtClass cc = pool.get("istic.fr.prog_test.PointTest");
```
L'objet `cc.getClass()` est bien de type `Class` mais il correspond à la classe `javassist.CtClass`  et pas à `istic.fr.prog_test.PointTest` comme souhaité. (`getClass()` est ici une méthode de `java.lang.Object` dont tout les objets java héritent, et non pas une méthode de javassist qui renverrait la classe représentée par un objet de type `CtClass`.)

Pour obtenir la classe désiré (`istic.fr.prog_test.PointTest`), il faut créer un classloader java et la charger.

Bref:
```java
            //On Crée un ClassLoader, on charge la classe de test désirée
            File testClassDir = new File("projetCible/target/test-classes");
            URL[] urls = new URL[]{testClassDir.toURL()};
            ClassLoader cl = new URLClassLoader(urls);

            //On lance JUnit sur la class de test
            JUnitCore junit = new JUnitCore();
            Result result = junit.run(cl.loadClass("fr.inria.AppTest"));
```

Attention, si la classe `istic.fr.prog_test.PointTest` ou les classes qu'elle test ont étées modifiées par javassist précédemment, ne pas oublier d'écrire les modifications pour que le classLoader les charge modifiées.

**Comment by PierreGaudichon** [comment]
C'est parfait, merci.
