### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nharrand** [PierreGaudichon/vev-dynamic-testing#7]
- [ ] Le projet ne se lance pas depuis un terminal.
- [ ] Les testes en l'état échouent. (Et leur couverture est faible)
- [ ] Pas encore de rapport

Attention, en l'état il est difficile d'évaluer le projet (même si je vois que du travail a été fait). Je rappel que l'évaluation porte sur trois aspects: implémentation, test et rapport. 

Je note également que seul deux d'entre vous contribuent au projet. (Et qu'a part la première et la dernière séance, je n'ai vu que deux d'entre vous.)

**Comment by PierreGaudichon** [comment]
Merci pour ce feedback.
Une fois qu'on aura réglé ces trois problèmes, si il reste du temps, on implementera la détection des branches conditionnelles.

**Comment by PierreGaudichon** [comment]
- Le projet ne se lance pas depuis un terminal.
  + *Toujours pas fait.* Un bug majeur nous en empêche.
- Les testes en l'état échouent. (Et leur couverture est faible)
  + *Fait.*
- Pas encore de rapport
  + *Fait.*
